package com.example.ft_hangouts.ui.theme

import androidx.compose.ui.graphics.Color

val bluePrimaryLight = Color(0xFF006972)
val blueonPrimaryLight = Color(0xFFFFFFFF)
val blueprimaryContainerLight = Color(0xFF9DF0FB)
val blueonPrimaryContainerLight = Color(0xFF004F56)
val bluesecondaryLight = Color(0xFF4A6366)
val blueonSecondaryLight = Color(0xFFFFFFFF)
val bluesecondaryContainerLight = Color(0xFFCDE7EB)
val blueonSecondaryContainerLight = Color(0xFF324B4E)
val bluetertiaryLight = Color(0xFF515E7D)
val blueonTertiaryLight = Color(0xFFFFFFFF)
val bluetertiaryContainerLight = Color(0xFFD8E2FF)
val blueonTertiaryContainerLight = Color(0xFF394664)
val blueerrorLight = Color(0xFFBA1A1A)
val blueonErrorLight = Color(0xFFFFFFFF)
val blueerrorContainerLight = Color(0xFFFFDAD6)
val blueonErrorContainerLight = Color(0xFF93000A)
val bluebackgroundLight = Color(0xFFF5FAFB)
val blueonBackgroundLight = Color(0xFF171D1D)
val bluesurfaceLight = Color(0xFFF5FAFB)
val blueonSurfaceLight = Color(0xFF171D1D)
val bluesurfaceVariantLight = Color(0xFFDAE4E6)
val blueonSurfaceVariantLight = Color(0xFF3F484A)
val blueoutlineLight = Color(0xFF6F797A)
val blueoutlineVariantLight = Color(0xFFBEC8CA)
val bluescrimLight = Color(0xFF000000)
val blueinverseSurfaceLight = Color(0xFF2B3132)
val blueinverseOnSurfaceLight = Color(0xFFECF2F2)
val blueinversePrimaryLight = Color(0xFF81D3DE)
val bluesurfaceDimLight = Color(0xFFD5DBDC)
val bluesurfaceBrightLight = Color(0xFFF5FAFB)
val bluesurfaceContainerLowestLight = Color(0xFFFFFFFF)
val bluesurfaceContainerLowLight = Color(0xFFEFF5F5)
val bluesurfaceContainerLight = Color(0xFFE9EFF0)
val bluesurfaceContainerHighLight = Color(0xFFE3E9EA)
val bluesurfaceContainerHighestLight = Color(0xFFDEE4E4)

val blueprimaryDark = Color(0xFF81D3DE)
val blueonPrimaryDark = Color(0xFF00363C)
val blueprimaryContainerDark = Color(0xFF004F56)
val blueonPrimaryContainerDark = Color(0xFF9DF0FB)
val bluesecondaryDark = Color(0xFFB1CBCF)
val blueonSecondaryDark = Color(0xFF1C3437)
val bluesecondaryContainerDark = Color(0xFF324B4E)
val blueonSecondaryContainerDark = Color(0xFFCDE7EB)
val bluetertiaryDark = Color(0xFFB9C6EA)
val blueonTertiaryDark = Color(0xFF22304D)
val bluetertiaryContainerDark = Color(0xFF394664)
val blueonTertiaryContainerDark = Color(0xFFD8E2FF)
val blueerrorDark = Color(0xFFFFB4AB)
val blueonErrorDark = Color(0xFF690005)
val blueerrorContainerDark = Color(0xFF93000A)
val blueonErrorContainerDark = Color(0xFFFFDAD6)
val bluebackgroundDark = Color(0xFF0E1415)
val blueonBackgroundDark = Color(0xFFDEE4E4)
val bluesurfaceDark = Color(0xFF0E1415)
val blueonSurfaceDark = Color(0xFFDEE4E4)
val bluesurfaceVariantDark = Color(0xFF3F484A)
val blueonSurfaceVariantDark = Color(0xFFBEC8CA)
val blueoutlineDark = Color(0xFF899294)
val blueoutlineVariantDark = Color(0xFF3F484A)
val bluescrimDark = Color(0xFF000000)
val blueinverseSurfaceDark = Color(0xFFDEE4E4)
val blueinverseOnSurfaceDark = Color(0xFF2B3132)
val blueinversePrimaryDark = Color(0xFF006972)
val bluesurfaceDimDark = Color(0xFF0E1415)
val bluesurfaceBrightDark = Color(0xFF343A3B)
val bluesurfaceContainerLowestDark = Color(0xFF090F10)
val bluesurfaceContainerLowDark = Color(0xFF171D1D)
val bluesurfaceContainerDark = Color(0xFF1B2121)
val bluesurfaceContainerHighDark = Color(0xFF252B2C)
val bluesurfaceContainerHighestDark = Color(0xFF303637)







