package com.example.compose
import androidx.compose.ui.graphics.Color

val purplePrimaryLight = Color(0xFF784F82)
val purpleonPrimaryLight = Color(0xFFFFFFFF)
val purpleprimaryContainerLight = Color(0xFFFBD7FF)
val purpleonPrimaryContainerLight = Color(0xFF5F3869)
val purplesecondaryLight = Color(0xFF6A596C)
val purpleonSecondaryLight = Color(0xFFFFFFFF)
val purplesecondaryContainerLight = Color(0xFFF2DBF3)
val purpleonSecondaryContainerLight = Color(0xFF514154)
val purpletertiaryLight = Color(0xFF82524E)
val purpleonTertiaryLight = Color(0xFFFFFFFF)
val purpletertiaryContainerLight = Color(0xFFFFDAD6)
val purpleonTertiaryContainerLight = Color(0xFF663B37)
val purpleerrorLight = Color(0xFFBA1A1A)
val purpleonErrorLight = Color(0xFFFFFFFF)
val purpleerrorContainerLight = Color(0xFFFFDAD6)
val purpleonErrorContainerLight = Color(0xFF93000A)
val purplebackgroundLight = Color(0xFFFFF7FB)
val purpleonBackgroundLight = Color(0xFF1F1A1F)
val purplesurfaceLight = Color(0xFFFFF7FB)
val purpleonSurfaceLight = Color(0xFF1F1A1F)
val purplesurfaceVariantLight = Color(0xFFEBDFE9)
val purpleonSurfaceVariantLight = Color(0xFF4C444C)
val purpleoutlineLight = Color(0xFF7E747D)
val purpleoutlineVariantLight = Color(0xFFCFC3CD)
val purplescrimLight = Color(0xFF000000)
val purpleinverseSurfaceLight = Color(0xFF342F34)
val purpleinverseOnSurfaceLight = Color(0xFFF8EEF5)
val purpleinversePrimaryLight = Color(0xFFE7B6F0)
val purplesurfaceDimLight = Color(0xFFE1D7DE)
val purplesurfaceBrightLight = Color(0xFFFFF7FB)
val purplesurfaceContainerLowestLight = Color(0xFFFFFFFF)
val purplesurfaceContainerLowLight = Color(0xFFFBF1F8)
val purplesurfaceContainerLight = Color(0xFFF5EBF2)
val purplesurfaceContainerHighLight = Color(0xFFF0E5EC)
val purplesurfaceContainerHighestLight = Color(0xFFEAE0E7)

val purpleprimaryDark = Color(0xFFE7B6F0)
val purpleonPrimaryDark = Color(0xFF462151)
val purpleprimaryContainerDark = Color(0xFF5F3869)
val purpleonPrimaryContainerDark = Color(0xFFFBD7FF)
val purplesecondaryDark = Color(0xFFD5C0D6)
val purpleonSecondaryDark = Color(0xFF3A2B3D)
val purplesecondaryContainerDark = Color(0xFF514154)
val purpleonSecondaryContainerDark = Color(0xFFF2DBF3)
val purpletertiaryDark = Color(0xFFF5B7B2)
val purpleonTertiaryDark = Color(0xFF4C2522)
val purpletertiaryContainerDark = Color(0xFF663B37)
val purpleonTertiaryContainerDark = Color(0xFFFFDAD6)
val purpleerrorDark = Color(0xFFFFB4AB)
val purpleonErrorDark = Color(0xFF690005)
val purpleerrorContainerDark = Color(0xFF93000A)
val purpleonErrorContainerDark = Color(0xFFFFDAD6)
val purplebackgroundDark = Color(0xFF161217)
val purpleonBackgroundDark = Color(0xFFEAE0E7)
val purplesurfaceDark = Color(0xFF161217)
val purpleonSurfaceDark = Color(0xFFEAE0E7)
val purplesurfaceVariantDark = Color(0xFF4C444C)
val purpleonSurfaceVariantDark = Color(0xFFCFC3CD)
val purpleoutlineDark = Color(0xFF988E97)
val purpleoutlineVariantDark = Color(0xFF4C444C)
val purplescrimDark = Color(0xFF000000)
val purpleinverseSurfaceDark = Color(0xFFEAE0E7)
val purpleinverseOnSurfaceDark = Color(0xFF342F34)
val purpleinversePrimaryDark = Color(0xFF784F82)
val purplesurfaceDimDark = Color(0xFF161217)
val purplesurfaceBrightDark = Color(0xFF3D373D)
val purplesurfaceContainerLowestDark = Color(0xFF110D12)
val purplesurfaceContainerLowDark = Color(0xFF1F1A1F)
val purplesurfaceContainerDark = Color(0xFF231E23)
val purplesurfaceContainerHighDark = Color(0xFF2E282E)
val purplesurfaceContainerHighestDark = Color(0xFF393339)



