package com.example.ft_hangouts.ui.theme

import android.app.Activity
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.SideEffect
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.toArgb
import androidx.compose.ui.platform.LocalView
import androidx.core.view.WindowCompat

private val blueLightScheme = lightColorScheme(
    primary = bluePrimaryLight,
    onPrimary = blueonPrimaryLight,
    primaryContainer = blueprimaryContainerLight,
    onPrimaryContainer = blueonPrimaryContainerLight,
    secondary = bluesecondaryLight,
    onSecondary = blueonSecondaryLight,
    secondaryContainer = bluesecondaryContainerLight,
    onSecondaryContainer = blueonSecondaryContainerLight,
    tertiary = bluetertiaryLight,
    onTertiary = blueonTertiaryLight,
    tertiaryContainer = bluetertiaryContainerLight,
    onTertiaryContainer = blueonTertiaryContainerLight,
    error = blueerrorLight,
    onError = blueonErrorLight,
    errorContainer = blueerrorContainerLight,
    onErrorContainer = blueonErrorContainerLight,
    background = bluebackgroundLight,
    onBackground = blueonBackgroundLight,
    surface = bluesurfaceLight,
    onSurface = blueonSurfaceLight,
    surfaceVariant = bluesurfaceVariantLight,
    onSurfaceVariant = blueonSurfaceVariantLight,
    outline = blueoutlineLight,
    outlineVariant = blueoutlineVariantLight,
    scrim = bluescrimLight,
    inverseSurface = blueinverseSurfaceLight,
    inverseOnSurface = blueinverseOnSurfaceLight,
    inversePrimary = blueinversePrimaryLight,
    surfaceDim = bluesurfaceDimLight,
    surfaceBright = bluesurfaceBrightLight,
    surfaceContainerLowest = bluesurfaceContainerLowestLight,
    surfaceContainerLow = bluesurfaceContainerLowLight,
    surfaceContainer = bluesurfaceContainerLight,
    surfaceContainerHigh = bluesurfaceContainerHighLight,
    surfaceContainerHighest = bluesurfaceContainerHighestLight,
)

private val blueDarkScheme = darkColorScheme(
    primary = blueprimaryDark,
    onPrimary = blueonPrimaryDark,
    primaryContainer = blueprimaryContainerDark,
    onPrimaryContainer = blueonPrimaryContainerDark,
    secondary = bluesecondaryDark,
    onSecondary = blueonSecondaryDark,
    secondaryContainer = bluesecondaryContainerDark,
    onSecondaryContainer = blueonSecondaryContainerDark,
    tertiary = bluetertiaryDark,
    onTertiary = blueonTertiaryDark,
    tertiaryContainer = bluetertiaryContainerDark,
    onTertiaryContainer = blueonTertiaryContainerDark,
    error = blueerrorDark,
    onError = blueonErrorDark,
    errorContainer = blueerrorContainerDark,
    onErrorContainer = blueonErrorContainerDark,
    background = bluebackgroundDark,
    onBackground = blueonBackgroundDark,
    surface = bluesurfaceDark,
    onSurface = blueonSurfaceDark,
    surfaceVariant = bluesurfaceVariantDark,
    onSurfaceVariant = blueonSurfaceVariantDark,
    outline = blueoutlineDark,
    outlineVariant = blueoutlineVariantDark,
    scrim = bluescrimDark,
    inverseSurface = blueinverseSurfaceDark,
    inverseOnSurface = blueinverseOnSurfaceDark,
    inversePrimary = blueinversePrimaryDark,
    surfaceDim = bluesurfaceDimDark,
    surfaceBright = bluesurfaceBrightDark,
    surfaceContainerLowest = bluesurfaceContainerLowestDark,
    surfaceContainerLow = bluesurfaceContainerLowDark,
    surfaceContainer = bluesurfaceContainerDark,
    surfaceContainerHigh = bluesurfaceContainerHighDark,
    surfaceContainerHighest = bluesurfaceContainerHighestDark,
)

private val greenLightScheme = lightColorScheme(
    primary = greenPrimaryLight,
    onPrimary = greenonPrimaryLight,
    primaryContainer = greenprimaryContainerLight,
    onPrimaryContainer = greenonPrimaryContainerLight,
    secondary = greensecondaryLight,
    onSecondary = greenonSecondaryLight,
    secondaryContainer = greensecondaryContainerLight,
    onSecondaryContainer = greenonSecondaryContainerLight,
    tertiary = greentertiaryLight,
    onTertiary = greenonTertiaryLight,
    tertiaryContainer = greentertiaryContainerLight,
    onTertiaryContainer = greenonTertiaryContainerLight,
    error = greenerrorLight,
    onError = greenonErrorLight,
    errorContainer = greenerrorContainerLight,
    onErrorContainer = greenonErrorContainerLight,
    background = greenbackgroundLight,
    onBackground = greenonBackgroundLight,
    surface = greensurfaceLight,
    onSurface = greenonSurfaceLight,
    surfaceVariant = greensurfaceVariantLight,
    onSurfaceVariant = greenonSurfaceVariantLight,
    outline = greenoutlineLight,
    outlineVariant = greenoutlineVariantLight,
    scrim = greenscrimLight,
    inverseSurface = greeninverseSurfaceLight,
    inverseOnSurface = greeninverseOnSurfaceLight,
    inversePrimary = greeninversePrimaryLight,
    surfaceDim = greensurfaceDimLight,
    surfaceBright = greensurfaceBrightLight,
    surfaceContainerLowest = greensurfaceContainerLowestLight,
    surfaceContainerLow = greensurfaceContainerLowLight,
    surfaceContainer = greensurfaceContainerLight,
    surfaceContainerHigh = greensurfaceContainerHighLight,
    surfaceContainerHighest = greensurfaceContainerHighestLight,
)

private val greenDarkScheme = darkColorScheme(
    primary = greenprimaryDark,
    onPrimary = greenonPrimaryDark,
    primaryContainer = greenprimaryContainerDark,
    onPrimaryContainer = greenonPrimaryContainerDark,
    secondary = greensecondaryDark,
    onSecondary = greenonSecondaryDark,
    secondaryContainer = greensecondaryContainerDark,
    onSecondaryContainer = greenonSecondaryContainerDark,
    tertiary = greentertiaryDark,
    onTertiary = greenonTertiaryDark,
    tertiaryContainer = greentertiaryContainerDark,
    onTertiaryContainer = greenonTertiaryContainerDark,
    error = greenerrorDark,
    onError = greenonErrorDark,
    errorContainer = greenerrorContainerDark,
    onErrorContainer = greenonErrorContainerDark,
    background = greenbackgroundDark,
    onBackground = greenonBackgroundDark,
    surface = greensurfaceDark,
    onSurface = greenonSurfaceDark,
    surfaceVariant = greensurfaceVariantDark,
    onSurfaceVariant = greenonSurfaceVariantDark,
    outline = greenoutlineDark,
    outlineVariant = greenoutlineVariantDark,
    scrim = greenscrimDark,
    inverseSurface = greeninverseSurfaceDark,
    inverseOnSurface = greeninverseOnSurfaceDark,
    inversePrimary = greeninversePrimaryDark,
    surfaceDim = greensurfaceDimDark,
    surfaceBright = greensurfaceBrightDark,
    surfaceContainerLowest = greensurfaceContainerLowestDark,
    surfaceContainerLow = greensurfaceContainerLowDark,
    surfaceContainer = greensurfaceContainerDark,
    surfaceContainerHigh = greensurfaceContainerHighDark,
    surfaceContainerHighest = greensurfaceContainerHighestDark,
)

private val pinkLightScheme = lightColorScheme(
    primary = pinkPrimaryLight,
    onPrimary = pinkonPrimaryLight,
    primaryContainer = pinkprimaryContainerLight,
    onPrimaryContainer = pinkonPrimaryContainerLight,
    secondary = pinksecondaryLight,
    onSecondary = pinkonSecondaryLight,
    secondaryContainer = pinksecondaryContainerLight,
    onSecondaryContainer = pinkonSecondaryContainerLight,
    tertiary = pinktertiaryLight,
    onTertiary = pinkonTertiaryLight,
    tertiaryContainer = pinktertiaryContainerLight,
    onTertiaryContainer = pinkonTertiaryContainerLight,
    error = pinkerrorLight,
    onError = pinkonErrorLight,
    errorContainer = pinkerrorContainerLight,
    onErrorContainer = pinkonErrorContainerLight,
    background = pinkbackgroundLight,
    onBackground = pinkonBackgroundLight,
    surface = pinksurfaceLight,
    onSurface = pinkonSurfaceLight,
    surfaceVariant = pinksurfaceVariantLight,
    onSurfaceVariant = pinkonSurfaceVariantLight,
    outline = pinkoutlineLight,
    outlineVariant = pinkoutlineVariantLight,
    scrim = pinkscrimLight,
    inverseSurface = pinkinverseSurfaceLight,
    inverseOnSurface = pinkinverseOnSurfaceLight,
    inversePrimary = pinkinversePrimaryLight,
    surfaceDim = pinksurfaceDimLight,
    surfaceBright = pinksurfaceBrightLight,
    surfaceContainerLowest = pinksurfaceContainerLowestLight,
    surfaceContainerLow = pinksurfaceContainerLowLight,
    surfaceContainer = pinksurfaceContainerLight,
    surfaceContainerHigh = pinksurfaceContainerHighLight,
    surfaceContainerHighest = pinksurfaceContainerHighestLight,
)

private val pinkDarkScheme = darkColorScheme(
    primary = pinkprimaryDark,
    onPrimary = pinkonPrimaryDark,
    primaryContainer = pinkprimaryContainerDark,
    onPrimaryContainer = pinkonPrimaryContainerDark,
    secondary = pinksecondaryDark,
    onSecondary = pinkonSecondaryDark,
    secondaryContainer = pinksecondaryContainerDark,
    onSecondaryContainer = pinkonSecondaryContainerDark,
    tertiary = pinktertiaryDark,
    onTertiary = pinkonTertiaryDark,
    tertiaryContainer = pinktertiaryContainerDark,
    onTertiaryContainer = pinkonTertiaryContainerDark,
    error = pinkerrorDark,
    onError = pinkonErrorDark,
    errorContainer = pinkerrorContainerDark,
    onErrorContainer = pinkonErrorContainerDark,
    background = pinkbackgroundDark,
    onBackground = pinkonBackgroundDark,
    surface = pinksurfaceDark,
    onSurface = pinkonSurfaceDark,
    surfaceVariant = pinksurfaceVariantDark,
    onSurfaceVariant = pinkonSurfaceVariantDark,
    outline = pinkoutlineDark,
    outlineVariant = pinkoutlineVariantDark,
    scrim = pinkscrimDark,
    inverseSurface = pinkinverseSurfaceDark,
    inverseOnSurface = pinkinverseOnSurfaceDark,
    inversePrimary = pinkinversePrimaryDark,
    surfaceDim = pinksurfaceDimDark,
    surfaceBright = pinksurfaceBrightDark,
    surfaceContainerLowest = pinksurfaceContainerLowestDark,
    surfaceContainerLow = pinksurfaceContainerLowDark,
    surfaceContainer = pinksurfaceContainerDark,
    surfaceContainerHigh = pinksurfaceContainerHighDark,
    surfaceContainerHighest = pinksurfaceContainerHighestDark,
)


private val purpleLightScheme = lightColorScheme(
    primary = purplePrimaryLight,
    onPrimary = purpleonPrimaryLight,
    primaryContainer = purpleprimaryContainerLight,
    onPrimaryContainer = purpleonPrimaryContainerLight,
    secondary = purplesecondaryLight,
    onSecondary = purpleonSecondaryLight,
    secondaryContainer = purplesecondaryContainerLight,
    onSecondaryContainer = purpleonSecondaryContainerLight,
    tertiary = purpletertiaryLight,
    onTertiary = purpleonTertiaryLight,
    tertiaryContainer = purpletertiaryContainerLight,
    onTertiaryContainer = purpleonTertiaryContainerLight,
    error = purpleerrorLight,
    onError = purpleonErrorLight,
    errorContainer = purpleerrorContainerLight,
    onErrorContainer = purpleonErrorContainerLight,
    background = purplebackgroundLight,
    onBackground = purpleonBackgroundLight,
    surface = purplesurfaceLight,
    onSurface = purpleonSurfaceLight,
    surfaceVariant = purplesurfaceVariantLight,
    onSurfaceVariant = purpleonSurfaceVariantLight,
    outline = purpleoutlineLight,
    outlineVariant = purpleoutlineVariantLight,
    scrim = purplescrimLight,
    inverseSurface = purpleinverseSurfaceLight,
    inverseOnSurface = purpleinverseOnSurfaceLight,
    inversePrimary = purpleinversePrimaryLight,
    surfaceDim = purplesurfaceDimLight,
    surfaceBright = purplesurfaceBrightLight,
    surfaceContainerLowest = purplesurfaceContainerLowestLight,
    surfaceContainerLow = purplesurfaceContainerLowLight,
    surfaceContainer = purplesurfaceContainerLight,
    surfaceContainerHigh = purplesurfaceContainerHighLight,
    surfaceContainerHighest = purplesurfaceContainerHighestLight,
)

private val purpleDarkScheme = darkColorScheme(
    primary = purpleprimaryDark,
    onPrimary = purpleonPrimaryDark,
    primaryContainer = purpleprimaryContainerDark,
    onPrimaryContainer = purpleonPrimaryContainerDark,
    secondary = purplesecondaryDark,
    onSecondary = purpleonSecondaryDark,
    secondaryContainer = purplesecondaryContainerDark,
    onSecondaryContainer = purpleonSecondaryContainerDark,
    tertiary = purpletertiaryDark,
    onTertiary = purpleonTertiaryDark,
    tertiaryContainer = purpletertiaryContainerDark,
    onTertiaryContainer = purpleonTertiaryContainerDark,
    error = purpleerrorDark,
    onError = purpleonErrorDark,
    errorContainer = purpleerrorContainerDark,
    onErrorContainer = purpleonErrorContainerDark,
    background = purplebackgroundDark,
    onBackground = purpleonBackgroundDark,
    surface = purplesurfaceDark,
    onSurface = purpleonSurfaceDark,
    surfaceVariant = purplesurfaceVariantDark,
    onSurfaceVariant = purpleonSurfaceVariantDark,
    outline = purpleoutlineDark,
    outlineVariant = purpleoutlineVariantDark,
    scrim = purplescrimDark,
    inverseSurface = purpleinverseSurfaceDark,
    inverseOnSurface = purpleinverseOnSurfaceDark,
    inversePrimary = purpleinversePrimaryDark,
    surfaceDim = purplesurfaceDimDark,
    surfaceBright = purplesurfaceBrightDark,
    surfaceContainerLowest = purplesurfaceContainerLowestDark,
    surfaceContainerLow = purplesurfaceContainerLowDark,
    surfaceContainer = purplesurfaceContainerDark,
    surfaceContainerHigh = purplesurfaceContainerHighDark,
    surfaceContainerHighest = purplesurfaceContainerHighestDark,
)

@Composable
fun Ft_hangoutsTheme(
    targetColor: Color = Color.Unspecified,
    darkTheme: Boolean = isSystemInDarkTheme(),
    // Dynamic color is available on Android 12+
    dynamicColor: Boolean = false,
    content: @Composable () -> Unit
) {
    val colorScheme = when(targetColor) {
        bluePrimaryLight -> if (darkTheme) blueDarkScheme else blueLightScheme
        greenPrimaryLight -> if (darkTheme) greenDarkScheme else greenLightScheme
        purplePrimaryLight -> if (darkTheme) purpleDarkScheme else purpleLightScheme
        pinkPrimaryLight -> if (darkTheme) pinkDarkScheme else pinkLightScheme
        else -> if (darkTheme) greenDarkScheme else greenLightScheme
    }

    val view = LocalView.current
    if (!view.isInEditMode) {
        SideEffect {
            val window = (view.context as Activity).window
            window.statusBarColor = colorScheme.primary.toArgb()
            WindowCompat.getInsetsController(window, view).isAppearanceLightStatusBars = !darkTheme
        }
    }

    MaterialTheme(
        colorScheme = colorScheme,
        typography = Typography,
        content = content
    )
}